### PR TITLE
fix: explain plan options

### LINKED ISSUE #1768: bug(python): explain_plan does not include prefiltering/scalar indices
### LanceDB version

_No response_

### What happened?

https://github.com/lancedb/lancedb/blob/04e1f1ee4c0c56efc86f7b36e9f08f06983f1de7/python/python/lancedb/query.py#L472-L504

From what I can see from the implementation here, we're not carrying forward `k`, `nprobes`, or `refine_factor` inside of the `nearest` argument and are not passing down any scalar filters/preflter designations.

### Are there known steps to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by gagan-bhullar-tech**
PR fixes #1768

### CODE REVIEW

**Review by wjones127 — COMMENTED** [review]
Did you see my comment https://github.com/lancedb/lancedb/issues/1768#issuecomment-2436458354 ? This is missing a lot more parameters still.

**Comment by gagan-bhullar-tech** [comment]
@wjones127 added parameters

**Review by wjones127 — CHANGES_REQUESTED** [review]
Thanks. That looks a bit better. Would still be nice to share the implementation so we don't duplicate the passing of these parameters. But for now, I think we can consider this to be fine.

Could you address the doctest error?

**Comment by gagan-bhullar-tech** [comment]
@wjones127 updated PR

**Review by wjones127 — APPROVED** [review]

**Pull request merged**
