### PR TITLE
bump lance to 0.9.7

### PR DESCRIPTION
**Pull request by albertlockett**

### CODE REVIEW

**Review by eddyxu — APPROVED** [review]
Do we need to bump python as well

**Review by chebbyChefNEQ — APPROVED** [review]

**Comment by albertlockett** [comment]
fixing some compiler errors.. moving to draft while fixing

**Comment by changhiskhan** [comment]
please bump python too while you're at it

**Review by changhiskhan — APPROVED** [review]
are there node and python tests for the index stats APIs? just want to make sure we're not breaking anything there

**Comment by albertlockett** [comment]
> are there node and python tests for the index stats APIs? just want to make sure we're not breaking anything there

Looks like we only have coverage on the node apis. I don't think we ever exposed it through the python api.

https://github.com/lancedb/lancedb/blob/119b928a52040f64dc8ac80e56cd2bc3b12874a3/node/src/test/test.ts#L475-L491

**Pull request merged**
