### PR TITLE
feat(python): add watsonx embeddings to registry

### PR DESCRIPTION
**Pull request by h0rv**
Related issue: https://github.com/lancedb/lancedb/issues/1412

### CODE REVIEW

**Comment by AyushExel** [comment]
Hey, thanks for the PR. Could you also add an optional test in the `test_embedding_functions_slow.py` test file?

**Comment by h0rv** [comment]
> Hey, thanks for the PR. Could you also add an optional test in the `test_embedding_functions_slow.py` test file?

@AyushExel, just added a test - working on setting up my local testing env now to validate it.

**Comment by h0rv** [comment]
Hi @AyushExel, got the test passing locally - validating the change.

Its ready for review now - thanks!

**Comment by AyushExel** [comment]
Looks good..The test failure is probably not related to this PR. I'll investigate

**Review by AyushExel — APPROVED** [review]

**Pull request merged**
