### PR TITLE
fix(python): add urllib3>=2.0.0 python dependency constraint

### PR DESCRIPTION
**Pull request by LuQQiu**
fixes https://github.com/lancedb/lancedb/issues/933

### CODE REVIEW

**Comment by wjones127** [comment]
Remind me, what do we use urllib for? I ask because I am removing the required dependency on `requests` in #1701

**Review by westonpace — APPROVED** [review]
@wjones127 we use `urllib3` in the python remote client (`client.py` and `connection_timeout.py`).  It appears it was added in https://github.com/lancedb/lancedb/pull/917 and https://github.com/lancedb/lancedb/pull/831

**Comment by westonpace** [comment]
> I ask because I am removing the required dependency on requests in https://github.com/lancedb/lancedb/pull/1701

Ah, I see.  Your PR does remove both files that were depending on `urllib3`.

**Comment by LuQQiu** [comment]
seems this is not needed anymore lol

**Comment by LuQQiu** [comment]
Close because this dependency is not needed anymore

**Pull request closed without merging**
