### PR TITLE
feat(python): add `bypass_vector_index` to sync api

### LINKED ISSUE #535: Add `bypass_vector_index` to Python sync API
We added this parameter to Node and Async Python in https://github.com/lancedb/lancedb/pull/1113.

* [ ] Add this to the Python sync API.
* [ ] Add a quick user guide on how to measure recall of a vector index using this.

This functionality is critical for debugging and measuring recall.

### PR DESCRIPTION
**Pull request by H3zi**
Hi lancedb team,

This PR adds the `bypass_vector_index` logic to the sync API, as described in [Issue #535](https://github.com/lancedb/lancedb/issues/535). (Closes #535).

Iv'e implemented it only for the regular vector search. If you think it should also be supported for FTS, Hybrid, or Empty queries and for the cloud solution, please let me know, and I’ll be happy to extend it.

Since there’s no `CONTRIBUTING.md` or contribution guidelines, I opted for the simplest implementation to get this started.

Looking forward to your feedback!

Thanks!

### CODE REVIEW

**Review by wjones127 — CHANGES_REQUESTED** [review]
Thanks @H3zi. Thanks for working on this. The implementation changes make sense.

You are right we don't have a `CONTRIBUTING.md` yet. I will add one. But my first piece of guidance is that we don't accept PRs for new features (or bug fixes) that don't have any unit tests. Please add some :)

If you're wondering how you can test `bypass_vector_index`, one tip is you can print out the `.explain_plan()` output and test for the absence of the index steps in the plan.

**Comment by wjones127** [comment]
> If you think it should also be supported for FTS, Hybrid, or Empty queries and for the cloud solution

Yes, it should be implemented for FTS, Hybrid, and empty queries.

For the Cloud API, you shouldn't need any additional changes. So I wouldn't worry about that.

**Comment by H3zi** [comment]
> > If you think it should also be supported for FTS, Hybrid, or Empty queries and for the cloud solution
> 
> Yes, it should be implemented for FTS, Hybrid, and empty queries.
> 
> For the Cloud API, you shouldn't need any additional changes. So I wouldn't worry about that.

Diving deeper, I’m uncertain about how `bypass_vector_index` is relevant to FTS, considering there’s no “vector” search involved. WDYT?

**Comment by wjones127** [comment]
> Diving deeper, I’m uncertain about how `bypass_vector_index` is relevant to FTS, considering there’s no “vector” search involved. WDYT?

Ah nevermind. It was originally just called `use_index`, so could also apply to FTS and scalar indices. But since it's now just for vector indices, it should only make sense on vector and hybrid searches.

**Comment by H3zi** [comment]
@wjones127  I’ve added the logic to `LanceHybridQueryBuilder` and included a test for the regular vector search case. However, I couldn’t find an existing synchronous hybrid query test to build upon for testing the bypass logic...

**Review by wjones127 — APPROVED** [review]
This is looking good. Thanks!

**Pull request merged**
