### PR TITLE
docs: add jina reranker to index

### PR DESCRIPTION
**Pull request by JoanFM**
PR to add JinaReranker documentation page to the rerankers index

### CODE REVIEW

**Comment by AyushExel** [comment]
A few other places you might want to add it for better visibility:
 - https://github.com/lancedb/lancedb/blob/main/docs/mkdocs.yml#L105
 - https://github.com/lancedb/lancedb/blob/main/docs/mkdocs.yml#L187
 - https://github.com/lancedb/lancedb/blob/main/docs/src/embeddings/default_embedding_functions.md

**Comment by JoanFM** [comment]
> A few other places you might want to add it for better visibility:
> 
> * https://github.com/lancedb/lancedb/blob/main/docs/mkdocs.yml#L105
> * https://github.com/lancedb/lancedb/blob/main/docs/mkdocs.yml#L187
> * https://github.com/lancedb/lancedb/blob/main/docs/src/embeddings/default_embedding_functions.md

Will do now!

**Comment by JoanFM** [comment]
> A few other places you might want to add it for better visibility:
> 
> * https://github.com/lancedb/lancedb/blob/main/docs/mkdocs.yml#L105
> * https://github.com/lancedb/lancedb/blob/main/docs/mkdocs.yml#L187
> * https://github.com/lancedb/lancedb/blob/main/docs/src/embeddings/default_embedding_functions.md

Hey @AyushExel ,

Now I realized a problem in my Implementation of Jina Embeddings.

What is the main API that needs to be considered, and how can I expect that a file path will be passed to the object.

It is hard for the MultiModal embedding to distinguish between a path and an actual string

**Comment by JoanFM** [comment]
> > A few other places you might want to add it for better visibility:
> > 
> > * https://github.com/lancedb/lancedb/blob/main/docs/mkdocs.yml#L105
> > * https://github.com/lancedb/lancedb/blob/main/docs/mkdocs.yml#L187
> > * https://github.com/lancedb/lancedb/blob/main/docs/src/embeddings/default_embedding_functions.md
> 
> Hey @AyushExel ,
> 
> Now I realized a problem in my Implementation of Jina Embeddings.
> 
> What is the main API that needs to be considered, and how can I expect that a file path will be passed to the object.
> 
> It is hard for the MultiModal embedding to distinguish between a path and an actual string

Actually, I am not sure that the documentation for OpenCLip embeddings is correct

**Comment by AyushExel** [comment]
@JoanFM hey, yeah I think the multi-modal embedding API is a little open ended on how source and query fields are treated. 
For open clip, here's whats happening:
 - It allows you to search images ( sourcefield) using images or text (vectorfield)
 - Here's how sourcefield is treated - https://github.com/lancedb/lancedb/blob/main/python/python/lancedb/embeddings/open_clip.py#L111
 - This basically means that a str when ingested will be treated as an image path.
 - In query mode, it accepts str or PIL. This basically allows you to search images via both text or images. https://github.com/lancedb/lancedb/blob/main/python/python/lancedb/embeddings/open_clip.py#L86
 
Eventually, we'll need to tighten up the API around how str is treated. RN its pretty loose and is just used to demonstrate how you can implement custom embedding functions. You can follow the same for Jina embedding API or add a better str/path handling logic if you want. (I think one way would be to simply treat str as text and pathlib object as path?).

**Comment by JoanFM** [comment]
> @JoanFM hey, yeah I think the multi-modal embedding API is a little open ended on how source and query fields are treated. For open clip, here's whats happening:
> 
> * It allows you to search images ( sourcefield) using images or text (vectorfield)
> * Here's how sourcefield is treated - https://github.com/lancedb/lancedb/blob/main/python/python/lancedb/embeddings/open_clip.py#L111
> * This basically means that a str when ingested will be treated as an image path.
> * In query mode, it accepts str or PIL. This basically allows you to search images via both text or images. https://github.com/lancedb/lancedb/blob/main/python/python/lancedb/embeddings/open_clip.py#L86
> 
> Eventually, we'll need to tighten up the API around how str is treated. RN its pretty loose and is just used to demonstrate how you can implement custom embedding functions. You can follow the same for Jina embedding API or add a better str/path handling logic if you want. (I think one way would be to simply treat str as text and pathlib object as path?).

But are you then sure that the examples in docs work?

**Comment by JoanFM** [comment]
Hey @AyushExel ,

I am getting this error:

```  File "pyarrow/table.pxi", line 4543, in pyarrow.lib.Table.append_column
  File "pyarrow/table.pxi", line 4500, in pyarrow.lib.Table.add_column
  File "pyarrow/error.pxi", line 154, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Added column's length must match table's length. Expected length 1 but got length 6
```
when running this example:


```python
import os
import requests
import lancedb
from lancedb.pydantic import LanceModel, Vector
from lancedb.embeddings import get_registry

os.environ['JINA_API_KEY'] = 'jina_*'

db = lancedb.connect("~/.lancedb")
func = get_registry().get("jina").create()


class Images(LanceModel):
    label: str
    image_uri: str = func.SourceField()  # image uri as the source
    image_bytes: bytes = func.SourceField()  # image bytes as the source
    vector: Vector(func.ndims()) = func.VectorField()  # vector column
    vec_from_bytes: Vector(func.ndims()) = func.VectorField()  # Another vector column


table = db.create_table("images", schema=Images)
labels = ["cat", "cat", "dog", "dog", "horse", "horse"]
uris = [
    "http://farm1.staticflickr.com/53/167798175_7c7845bbbd_z.jpg",
    "http://farm1.staticflickr.com/134/332220238_da527d8140_z.jpg",
    "http://farm9.staticflickr.com/8387/8602747737_2e5c2a45d4_z.jpg",
    "http://farm5.staticflickr.com/4092/5017326486_1f46057f5f_z.jpg",
    "http://farm9.staticflickr.com/8216/8434969557_d37882c42d_z.jpg",
    "http://farm6.staticflickr.com/5142/5835678453_4f3a4edb45_z.jpg",
]
# get each uri as bytes
image_bytes = [requests.get(uri).content for uri in uris]
table.add(
    [{"label": labels, "image_uri": uris, "image_bytes": image_bytes}]
)
```

I believe it may be due to `ChunkedArrays` or something like that, but it is not clear how to handle on my side. I put it as draft until this is clarified

**Comment by JoanFM** [comment]
Also, I see a Linting error that the OpenCLIP also does not fullfil

**Comment by AyushExel** [comment]
> > @JoanFM hey, yeah I think the multi-modal embedding API is a little open ended on how source and query fields are treated. For open clip, here's whats happening:
> > 
> > * It allows you to search images ( sourcefield) using images or text (vectorfield)
> > * Here's how sourcefield is treated - https://github.com/lancedb/lancedb/blob/main/python/python/lancedb/embeddings/open_clip.py#L111
> > * This basically means that a str when ingested will be treated as an image path.
> > * In query mode, it accepts str or PIL. This basically allows you to search images via both text or images. https://github.com/lancedb/lancedb/blob/main/python/python/lancedb/embeddings/open_clip.py#L86
> > 
> > Eventually, we'll need to tighten up the API around how str is treated. RN its pretty loose and is just used to demonstrate how you can implement custom embedding functions. You can follow the same for Jina embedding API or add a better str/path handling logic if you want. (I think one way would be to simply treat str as text and pathlib object as path?).
> 
> But are you then sure that the examples in docs work?

ohh I didn't check the example. I meant the openCLIP Embedding API in general. I'll get to this now

**Comment by AyushExel** [comment]
@JoanFM srry yeah the example code was broken. table.add accepts list of dicts, pandas or arrow batch.
It should be like this:
```
import os
import requests
import lancedb
from lancedb.pydantic import LanceModel, Vector
from lancedb.embeddings import get_registry

os.environ['JINA_API_KEY'] = 'jina_*'

db = lancedb.connect("~/.lancedb")
func = get_registry().get("jina").create()


class Images(LanceModel):
    label: str
    image_uri: str = func.SourceField()  # image uri as the source
    image_bytes: bytes = func.SourceField()  # image bytes as the source
    vector: Vector(func.ndims()) = func.VectorField()  # vector column
    vec_from_bytes: Vector(func.ndims()) = func.VectorField()  # Another vector column


table = db.create_table("images", schema=Images)
labels = ["cat", "cat", "dog", "dog", "horse", "horse"]
uris = [
    "http://farm1.staticflickr.com/53/167798175_7c7845bbbd_z.jpg",
    "http://farm1.staticflickr.com/134/332220238_da527d8140_z.jpg",
    "http://farm9.staticflickr.com/8387/8602747737_2e5c2a45d4_z.jpg",
    "http://farm5.staticflickr.com/4092/5017326486_1f46057f5f_z.jpg",
    "http://farm9.staticflickr.com/8216/8434969557_d37882c42d_z.jpg",
    "http://farm6.staticflickr.com/5142/5835678453_4f3a4edb45_z.jpg",
]
# get each uri as bytes
image_bytes = [requests.get(uri).content for uri in uris]
table.add(
  pd.DataFrame({"label": labels, "image_uri": uris, "image_bytes": image_bytes})
)

```
I will fix openCLIP example in another PR. But for jina, I'm seeing this error on trying to run the code now:
 `TypeError('Object of type bytes is not JSON serializable')`

**Review by AyushExel — APPROVED** [review]

**Pull request merged**
