### PR TITLE
feat(python): drop support for dictionary in Table.add

### LINKED ISSUE #1706: Feature: drop support for dictionary as DATA in `Table.add()`
### SDK

Python

### Description

It's confusing and broken, as illustrated in this issue: https://github.com/lancedb/lancedb/issues/1705#issuecomment-2379540005

We could change it to accept a dictionary as a single row. But we want to nudge users away from writing one row at a time anyways. So better to just not accept a dictionary type.

### PR DESCRIPTION
**Pull request by gagan-bhullar-tech**
PR closes #1706

### CODE REVIEW

**Comment by gagan-bhullar-tech** [comment]
@wjones127 please review

**Review by wjones127 — CHANGES_REQUESTED** [review]
Thank you for working on this. Here's a few other changes you will need to make:

* Change the type definition of `DATA` to not include `dict` anymore
   * https://github.com/lancedb/lancedb/blob/e61ba7f4e21ed801912e9ea75f07d8c40b29adc2/python/python/lancedb/common.py#L23
* Change docstrings for every method that also uses the `DATA` type as a paramter. Such as `create_table`.
* Please add a test asserting that a user gets a clear error message if they pass a dictionary. It should say something like: "Cannot add a single dictionary to a table. Use a list."
  * Can be similar to this error message: https://github.com/lancedb/lancedb/blob/e61ba7f4e21ed801912e9ea75f07d8c40b29adc2/python/python/lancedb/table.py#L87-L88

**Comment by gagan-bhullar-tech** [comment]
@wjones127 updated PR. Please review.

**Review by wjones127 — APPROVED** [review]
Excellent work. Thank you!

**Pull request merged**
