### PR TITLE
feat!: upgrade Lance to 0.18.0

### PR DESCRIPTION
**Pull request by LuQQiu**
BREAKING CHANGE: default file format changed to Lance v2.0.

Upgrade Lance to 0.18.0

Change notes: https://github.com/lancedb/lance/releases/tag/v0.18.0

### CODE REVIEW

**Comment by LuQQiu** [comment]
Nodejs failed with 
```
  ● Given a table › should overwrite data if asked

    Failed to add batches to table some_table: lance error: Encountered internal error. Please file a bug report at https://github.com/lancedb/lance/issues. The operation added files with version 0.1.  However, the data storage version is 2.0., /Users/lu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lance-0.18.0/src/io/commit.rs:233:31

```

**Comment by LuQQiu** [comment]
> Nodejs failed with
> 
> ```
>   ● Given a table › should overwrite data if asked
> 
>     Failed to add batches to table some_table: lance error: Encountered internal error. Please file a bug report at https://github.com/lancedb/lance/issues. The operation added files with version 0.1.  However, the data storage version is 2.0., /Users/lu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lance-0.18.0/src/io/commit.rs:233:31
> ```



> Nodejs failed with
> 
> ```
>   ● Given a table › should overwrite data if asked
> 
>     Failed to add batches to table some_table: lance error: Encountered internal error. Please file a bug report at https://github.com/lancedb/lance/issues. The operation added files with version 0.1.  However, the data storage version is 2.0., /Users/lu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lance-0.18.0/src/io/commit.rs:233:31
> ```

**Comment by LuQQiu** [comment]
failures:

---- connection::tests::test_create_table_v2 stdout ----
thread 'connection::tests::test_create_table_v2' panicked at rust/lancedb/src/connection.rs:1259:9:
assertion `left == right` failed
  left: 1
 right: 20
stack backtrace:
   0: rust_begin_unwind
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
   2: core::panicking::assert_failed_inner
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:409:17
   3: core::panicking::assert_failed
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:364:5
   4: lancedb::connection::tests::test_create_table_v2::{{closure}}
             at ./src/connection.rs:1259:9
   5: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/future/future.rs:123:9
   6: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/future/future.rs:123:9
   7: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:696:57
   8: tokio::runtime::coop::with_budget
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/coop.rs:107:5
   9: tokio::runtime::coop::budget
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/coop.rs:73:5
  10: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:696:25
  11: tokio::runtime::scheduler::current_thread::Context::enter
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:423:19
  12: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:695:36
  13: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:774:68
  14: tokio::runtime::context::scoped::Scoped<T>::set
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context/scoped.rs:40:9
  15: tokio::runtime::context::set_scheduler::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context.rs:180:26
  16: std::thread::local::LocalKey<T>::try_with
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/thread/local.rs:286:12
  17: std::thread::local::LocalKey<T>::with
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/thread/local.rs:262:9
  18: tokio::runtime::context::set_scheduler
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context.rs:180:9
  19: tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:774:27
  20: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:683:19
  21: tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:191:28
  22: tokio::runtime::context::runtime::enter_runtime
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context/runtime.rs:65:16
  23: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:[179](https://github.com/lancedb/lancedb/actions/runs/10911949398/job/30285678555?pr=1657#step:8:180):9
  24: tokio::runtime::runtime::Runtime::block_on_inner
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/runtime.rs:361:47
  25: tokio::runtime::runtime::Runtime::block_on
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/runtime.rs:335:13
  26: lancedb::connection::tests::test_create_table_v2
             at ./src/connection.rs:1281:9
  27: lancedb::connection::tests::test_create_table_v2::{{closure}}
             at ./src/connection.rs:1236:36
  28: core::ops::function::FnOnce::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
  29: core::ops::function::FnOnce::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by LuQQiu** [comment]
Python windows test error is a known race condition
=========================== short test summary info ===========================
FAILED python\python\tests\test_table.py::test_restore_consistency - assert 2 == 3
 +  where 2 = LanceTable(connection=LanceDBConnection(C:\Users\runneradmin\AppData\Local\Temp\pytest-of-runneradmin\pytest-0\test_restore_consistency0, read_consistency_interval=datetime.timedelta(0)), name="my_table").version
 +  and   3 = LanceTable(connection=LanceDBConnection(C:\Users\runneradmin\AppData\Local\Temp\pytest-of-runneradmin\pytest-0\test_restore_consistency0), name="my_table").version
!!!!!!!!!!!!!!!!!!!!!!!!!! stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!
==== 1 failed, 126 passed, 18 skipped, 19 deselected, 3 warnings in 31.28s ====

**Comment by wjones127** [comment]
Some notes on upgrading Lance:

1. We should label as a `feat` to make this visible in the change notes. `chore` is hidden from the generated change log in our releases.
2. We should link to the changelog of the Lance version from the PR, to make it easy to find.
3. If there are breaking changes in Lance that affect LanceDB, we should label this a breaking change.

**Comment by wjones127** [comment]
Could you actually change the docs in this upgrade for the default of `dataStorageVersion`?

I think you just need to update here: 

https://github.com/lancedb/lancedb/blob/ffb28dd4fc204b89d46ece4a60c03d331f11d591/python/python/lancedb/db.py#L613

This should also now default to false:

https://github.com/lancedb/lancedb/blob/ffb28dd4fc204b89d46ece4a60c03d331f11d591/python/python/lancedb/db.py#L618

Also here in rust docs: 

https://github.com/lancedb/lancedb/blob/ffb28dd4fc204b89d46ece4a60c03d331f11d591/rust/lancedb/src/connection.rs#L310

And then in Node, this codepath should change to default to stable:

https://github.com/lancedb/lancedb/blob/ffb28dd4fc204b89d46ece4a60c03d331f11d591/nodejs/lancedb/connection.ts#L306-L311

**Comment by westonpace** [comment]
> Could you actually change the docs in this upgrade for the default of dataStorageVersion?

Are we upgrading the default in LanceDB to also be v2?  That is probably ok.  My initial assumption was we would hard-code to v1 for some amount of time.  But I can't think of a great reason to force that.

**Comment by wjones127** [comment]
> Are we upgrading the default in LanceDB to also be v2? That is probably ok. My initial assumption was we would hard-code to v1 for some amount of time. But I can't think of a great reason to force that.

I'm fine to not upgrade. It's just that many of the places just pass through to the default of Lance. Do you want to change so we don't?

**Comment by LuQQiu** [comment]
TODO
- bump the version to 0.11.0 <-- minor version jump
- do some changes to use new V2 version
- address docs to refer to V2

release v0.11.0-beta.0

**Comment by LuQQiu** [comment]
@wjones127 @westonpace Change to consistently use Lance V2 format as the default, PTAL, thanks!

**Review by wjones127 — APPROVED** [review]

**Pull request merged**
