### PR TITLE
feat(nodejs): table.search functionality

### PR DESCRIPTION
**Pull request by universalmind303**
closes https://github.com/lancedb/lancedb/issues/1256

### CODE REVIEW

**Comment by universalmind303** [comment]
@wjones127 
> My main question is whether we want to have a new search() method, or are we fine just using query()? Or, put another way, why not just make nearestTo take the string/embedd-able data?

good question. We could instead make `query` take in the string parameter instead. 

I think intuitively `.query("some string")` feels much more natural than starting the builder first. `.query().nearestTo("some string")`.

**Comment by wjones127** [comment]
> I think intuitively .query("some string") feels much more natural than starting the builder first.

I think the idea is that `query` is more general than `search`. The `query` API can also be used to do a `scan`.

**Review by wjones127 — APPROVED** [review]
I think I'm good with having the separate `search()` API given the precedence in the Python sync API.

**Comment by universalmind303** [comment]
@wjones127 @westonpace Do we have any way to run CI without cache? It seems like it's using cached code 

>  `Error: lancedb/table.ts(146,7): error TS2663: Cannot find name 'schema'. Did you mean the instance member 'this.schema'?`

`lancedb/table.ts(146,7)` has no reference to `schema`

**Pull request merged**
